In [3]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('COVID19 cases Toronto.csv')

In [15]:

# Visualizando cabeçalho de um dataframe
df.head()

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
0,44294,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No
1,44295,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No
2,44296,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes
3,44297,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No
4,44298,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No

In [16]:
# Verificando informações sobre o dataframe e suas colunas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14911 entries, 0 to 14910
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     14911 non-null  int64
 1   Outbreak Associated     14911 non-null  object
 2   Age Group               14879 non-null  object
 3   Neighbourhood Name      14298 non-null  object
 4   FSA                     14344 non-null  object
 5   Source of Infection     14911 non-null  object
 6   Classification          14911 non-null  object
 7   Episode Date            14911 non-null  object
 8   Reported Date           14911 non-null  object
 9   Client Gender           14911 non-null  object
 10  Outcome                 14911 non-null  object
 11  Currently Hospitalized  14911 non-null  object
 12  Currently in ICU        14911 non-null  object
 13  Currently Intubated     14911 non-null  object
 14  Ever Hospitalized       14911 non-null  object
 15  Ever in ICU             14911 non-null  object
 16  Ever Intubated          14911 non-null  object
dtypes: int64(1), object(16)
memory usage: 1.9+ MB

In [17]:
# Descrevendo estatísticas sobre os dados
df.describe(include='all')

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
count,14911.000000,14911,14879,14298,14344,14911,14911,14911,14911,14911,14911,14911,14911,14911,14911,14911,14911
unique,NaN,2,9,140,96,8,2,149,142,5,3,2,2,2,2,2,2
top,NaN,Sporadic,50-59,Glenfield-Jane Heights,M9V,N/A - Outbreak associated,CONFIRMED,2020-04-15,2020-05-29,FEMALE,RESOLVED,No,No,No,No,No,No
freq,NaN,9333,2354,502,850,5578,13686,292,437,7909,13195,14760,14882,14886,13063,14511,14624
mean,51749.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,4304.579267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,44294.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,48021.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,51749.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,55476.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,59204.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Tratando dados ausentes

# Verificando dados nulos
df.isnull().head(6)

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [20]:
# Verificando dados nulos para cada coluna
df.isnull().sum()

_id                         0
Outbreak Associated         0
Age Group                  32
Neighbourhood Name        613
FSA                       567
Source of Infection         0
Classification              0
Episode Date                0
Reported Date               0
Client Gender               0
Outcome                     0
Currently Hospitalized      0
Currently in ICU            0
Currently Intubated         0
Ever Hospitalized           0
Ever in ICU                 0
Ever Intubated              0
dtype: int64

In [21]:
# Dropando dados de um dataframe. O método dropna() é equivalente a "df[df.notnull()]"
shape_before = df.shape[0]
shape_curr = df.dropna().shape[0]
print("{} linhas foram removidas, o que é equivalente a {}% do dataset".format(shape_before - shape_curr, round((shape_before - shape_curr) / shape_before * 100, 2)))

637 linhas foram removidas, o que é equivalente a 4.27% do dataset

In [27]:
# Using concat() instead of the deprecated append() method
df = pd.concat([df, pd.DataFrame([{}])], ignore_index=True)
# Alternative approach using loc
# df.loc[len(df)] = pd.Series()
df.tail()

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
14910,59204.0,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No
14911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
shape_before = df.shape[0]
shape_curr = df.dropna(how='all').shape[0]
print("{} linhas foram removidas, o que é equivalente a {}% do dataset".format(shape_before - shape_curr, round((shape_before - shape_curr) / shape_before * 100, 2)))

4 linhas foram removidas, o que é equivalente a 0.03% do dataset

In [53]:
df.tail()

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated,Nulo
14910,59204.0,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,NaN
14911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
#Adiciona coluna nula
df['Nulo'] = np.nan

In [44]:
df.head()

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated,Nulo
0,44294.0,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No,NaN
1,44295.0,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No,NaN
2,44296.0,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes,NaN
3,44297.0,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No,NaN
4,44298.0,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No,NaN

In [69]:
 df = df.dropna(axis=1, how='all')

In [63]:
 df.dropna(axis=1, thresh=2)

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
0,44294.0,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No
1,44295.0,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No
2,44296.0,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes
3,44297.0,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No
4,44298.0,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14910,59204.0,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No
14911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df.fillna("")

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated,Nulo
0,44294.0,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No,
1,44295.0,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No,
2,44296.0,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes,
3,44297.0,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No,
4,44298.0,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14910,59204.0,Outbreak Associated,50-59,,,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,
14911,,,,,,,,,,,,,,,,,,
14912,,,,,,,,,,,,,,,,,,
14913,,,,,,,,,,,,,,,,,,
14914,,,,,,,,,,,,,,,,,,

In [57]:
# Preenchendo dados ausentes com valores específicos por coluna
df.fillna(value={'Age Group': 'Não tem', 'Classification': 'Sem Status'})

# df.fillna(method='ffill') pode ser utilizado como método de interpolação para dados ausentes
df.tail()

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated,Nulo
14910,59204.0,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,NaN
14911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df.fillna(method='ffill').tail()

C:\Users\gugaa\AppData\Local\Temp\ipykernel_10852\3401144114.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill').tail()

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated,Nulo
14910,59204.0,Outbreak Associated,50-59,West Humber-Clairville,M9C,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,NaN
14911,59204.0,Outbreak Associated,50-59,West Humber-Clairville,M9C,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,NaN
14912,59204.0,Outbreak Associated,50-59,West Humber-Clairville,M9C,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,NaN
14913,59204.0,Outbreak Associated,50-59,West Humber-Clairville,M9C,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,NaN
14914,59204.0,Outbreak Associated,50-59,West Humber-Clairville,M9C,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,NaN

In [76]:
# Preenchendo com a média
#df.fillna(df.mean())
# Preenchendo com a média
# First convert numeric columns to numeric type, then fill NaN values
# For numeric columns only
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
df
# For string columns (if needed)
# string_cols = df.select_dtypes(include=['object']).columns
# df[string_cols] = df[string_cols].fillna(df[string_cols].mode().iloc[0])

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
0,44294.0,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No
1,44295.0,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No
2,44296.0,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes
3,44297.0,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No
4,44298.0,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14910,59204.0,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No
14911,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14912,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14913,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14914,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# Preenchendo com a moda
df.fillna(df.mode().iloc[0])

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated,Nulo
0,44294.0,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No,NaN
1,44295.0,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No,NaN
2,44296.0,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes,NaN
3,44297.0,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No,NaN
4,44298.0,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14910,59204.0,Outbreak Associated,50-59,Glenfield-Jane Heights,M9V,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No,NaN
14911,44294.0,Sporadic,50-59,Glenfield-Jane Heights,M9V,N/A - Outbreak associated,CONFIRMED,2020-04-15,2020-05-29,FEMALE,RESOLVED,No,No,No,No,No,No,NaN
14912,44294.0,Sporadic,50-59,Glenfield-Jane Heights,M9V,N/A - Outbreak associated,CONFIRMED,2020-04-15,2020-05-29,FEMALE,RESOLVED,No,No,No,No,No,No,NaN
14913,44294.0,Sporadic,50-59,Glenfield-Jane Heights,M9V,N/A - Outbreak associated,CONFIRMED,2020-04-15,2020-05-29,FEMALE,RESOLVED,No,No,No,No,No,No,NaN
14914,44294.0,Sporadic,50-59,Glenfield-Jane Heights,M9V,N/A - Outbreak associated,CONFIRMED,2020-04-15,2020-05-29,FEMALE,RESOLVED,No,No,No,No,No,No,NaN

In [78]:
# Preenchendo com a mediana
#df.fillna(df.median().iloc[0])

numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
df

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
0,44294.0,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No
1,44295.0,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No
2,44296.0,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes
3,44297.0,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No
4,44298.0,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14910,59204.0,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No
14911,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14912,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14913,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14914,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
14910    False
14911    False
14912     True
14913     True
14914     True
Length: 14915, dtype: bool

In [79]:
df[df.duplicated()]

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
14912,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14913,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14914,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
df.drop_duplicates(keep='last')

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated
0,44294.0,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No
1,44295.0,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No
2,44296.0,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes
3,44297.0,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No
4,44298.0,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14907,59201.0,Outbreak Associated,20-29,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-05-09,2020-05-23,FEMALE,RESOLVED,No,No,No,No,No,No
14908,59202.0,Outbreak Associated,40-49,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-18,2020-06-19,FEMALE,RESOLVED,No,No,No,No,No,No
14909,59203.0,Outbreak Associated,19 and younger,NaN,NaN,N/A - Outbreak associated,PROBABLE,2020-06-13,2020-06-13,MALE,RESOLVED,No,No,No,No,No,No
14910,59204.0,Outbreak Associated,50-59,NaN,NaN,N/A - Outbreak associated,CONFIRMED,2020-06-22,2020-06-23,FEMALE,RESOLVED,No,No,No,Yes,No,No
14914,51749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
np.nan is not np.nan

False

In [88]:
df['year'] = df['Reported Date'].map(lambda x: str(x)[0:4] if x is not np.nan else np.nan)

df['year']

0        2020
1        2020
2        2020
3        2020
4        2020
         ...
14910    2020
14911     NaN
14912     NaN
14913     NaN
14914     NaN
Name: year, Length: 14915, dtype: object

In [90]:
df['day'] = df['Reported Date'].map(lambda x: int(str(x)[-2:]) if x is not np.nan else np.nan)
df['day']

0        27.0
1        28.0
2         8.0
3         4.0
4         6.0
         ...
14910    23.0
14911     NaN
14912     NaN
14913     NaN
14914     NaN
Name: day, Length: 14915, dtype: float64

In [92]:
bins = [0, 10, 20, 31]
periodo_mes = pd.cut(df['day'].to_numpy(), bins=bins)

In [93]:
df['periodo_mes'] = periodo_mes

In [94]:
df['periodo_mes'].value_counts()

periodo_mes
(20, 31]    5124
(10, 20]    5028
(0, 10]     4759
Name: count, dtype: int64

In [95]:
bins = [0, 10, 20, 31]
df['periodo_mes'] = pd.cut(df['day'].to_numpy(), bins=bins, labels=['inicio_mes', 'meio_mes', 'fim_mes'])

df.head()

,_id,Outbreak Associated,Age Group,Neighbourhood Name,FSA,Source of Infection,Classification,Episode Date,Reported Date,Client Gender,Outcome,Currently Hospitalized,Currently in ICU,Currently Intubated,Ever Hospitalized,Ever in ICU,Ever Intubated,year,day,periodo_mes
0,44294.0,Sporadic,50-59,Malvern,M1B,Institutional,CONFIRMED,2020-03-25,2020-03-27,MALE,RESOLVED,No,No,No,No,No,No,2020,27.0,fim_mes
1,44295.0,Sporadic,20-29,Malvern,M1B,Community,CONFIRMED,2020-03-20,2020-03-28,MALE,RESOLVED,No,No,No,Yes,No,No,2020,28.0,fim_mes
2,44296.0,Sporadic,60-69,Malvern,M1B,Travel,CONFIRMED,2020-03-04,2020-03-08,FEMALE,RESOLVED,No,No,No,Yes,Yes,Yes,2020,8.0,inicio_mes
3,44297.0,Outbreak Associated,50-59,Rouge,M1B,N/A - Outbreak associated,CONFIRMED,2020-05-02,2020-05-04,FEMALE,RESOLVED,No,No,No,No,No,No,2020,4.0,inicio_mes
4,44298.0,Sporadic,30-39,Rouge,M1B,Close contact,CONFIRMED,2020-05-31,2020-06-06,FEMALE,RESOLVED,No,No,No,No,No,No,2020,6.0,inicio_mes

In [99]:
shape_before = df.shape[0]
shape_curr = df.drop(df[df['day'] < 15].index).shape[0]
print("{} linhas foram removidas, o que é equivalente a {}% do dataset".format(shape_before - shape_curr, round((shape_before - shape_curr) / shape_before * 100, 2)))

6533 linhas foram removidas, o que é equivalente a 43.8% do dataset